### ISSUE TITLE
Several questions/requests.

### ISSUE THREAD

**Issue by 3space123** [techyowl/WinkWeb#1]
Your work is great!  Thank you so much.  I was looking exactly for this.  I had already been playing with Beam's code from Google+, that you referenced in your ReadMe.  Many of the same opportunities for layout improvement, etc. I noticed with his code are still not optimal here, but you have spent a lot more time on your interface, and it shows.  The pop-up for mac desktop is really nice as well!  Great idea!

A few questions:
1. How would this best be set up for iOS Safari-based control?
2. Are you planning on expanding to allow control of blinds (I have 4 Lutron Serena shades)?
3. What are your plans for future development?  Or is this it in terms of releases?
4. Do you need help with testing?  I have 65 devices connected to two Wink hubs, and would be happy to help.

**Comment by blaineam** [comment]
Well the code that I got from the google plus account was in no way complete. It had some support but needs a lot more work to expand its products. I may try to build it out further when I get extra time which probably won't be too far in the future. As for iOS Safari I'd assume using the official wink app would be a better option. But I have a build over at [link to wink web site](http://wink.blainemiller.xyz). I think I will setup a feature to send out the device code so that people much like yourself can easily email me the response from wink which has to get processed to support the devices. As for the interface it needs more work but should work on a variety of screen sizes. I do plan to expand this either through third party contributions or by myself over time. Later I will need testing but I have a pretty decent wink home device list as well although I don't have blinds. I may also add a passive API that can be sent to the web interface to control things with using the preset cookie as authentication. Not sure fully but it's a potential idea. Hope this answers your questions. Stay tuned for the next release.

**Comment by blaineam** [comment]
Latest build has the debug menu option and some bug fixes to the safari app I didn't now were there feel free to send the msg it generates to me. This will allow me to better develop the wink web device support. Its only needed one time per device list so until you add new types of devices the last message will do. I'd also like to reiterate that no personal information is sent to me just a response from the wink api that gets processed to support devices.

**Comment by 3space123** [comment]
Thank you for the in-depth response.  It is much appreciated.  The problem with the iOS app is that the layout is obscenely inadequate.  on my iPhone, it's OK, but when I load onto my iPad Pro, it's crazy.  Only 6 devices can be viewed on the 12" screen at a time.  That means each icon is approximately 6cm x 6cm in size.  I was hoping to have true whole-screen control of my various devices.  I asked Wink about it, and they indicated that they had no immediate plans to support alternative layouts, skinning, etc.  Again, thank you.  Will check out the debug option.
